version: '2'
services:
    frontend:
        build: frontend/
        command: npm start
        ports: 
            - "80:8080"
    backend:
        build: backend/
        command: npm run watch
    mongodb:
        image: mongo:latest
        volumes:
            - ./db:/data/db