version: '2'
services:
    frontend:
        build: frontend/
        command: npm start
        # ports: 
        #     - "80:8080"
    backend:
        build: backend/
        command: npm run watch
    mongodb:
        image: mongo:latest
        volumes:
            - ./db:/data/db
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - URL=poesie.pics
            - VALIDATION=http
            - ONLY_SUBDOMAINS=false #optional
            - STAGING=false #optional
        volumes:
            - ./swag:/config:z
        ports:
            - 443:443
            - 80:80 #optional
        restart: unless-stopped
  